# Site settings
title: Forever Genin
email: hello@forevergenin.com
description: > # this means to ignore newlines until "baseurl:"
  Powered by GitHub
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.forevergenin.com" # the base hostname & protocol for your site
twitter_username: forevergenin
github_username:  forevergenin
timezone: Asia/Kolkata

# Build settings
markdown: kramdown

## Octopress settings

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft
